name: Joe + Code
author: Joseph Obiajulu
url: "https://obiajulu.github.io"
baseurl: "/obiajulu.github.io"
description: a Julia SOC blog
github: http://www.github.com/obiajulu
#twitter: http://www.twitter.com/
#facebook: http://www.facebook.com
#linkedin: http://www.linkedin.com
email: obiajulu[at]princeton.edu
#disqus: obiajulu

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
